### PR TITLE
Simple program to print entries from a file, without the additional files

### PR DESCRIPTION
**Pull request by WillYingling**

### CODE REVIEW

**Review by ramrunner — CHANGES_REQUESTED** [review]
Hi there Will! thanks for the pull request.
some comments: it's good practice to squash history before we actually merge look at this:

https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

other minor things:
name the binary: indextool
that i:=0 i++.. why not len() it?
finally: maybe a bit of overengineering for this case but it would be good practice:
imagine: f bgp.ArchEntryFile had a String() function it would satisfy the Stringer interface and you could print it straightaway like
fmt.Printf("%s\n", entry)
now... if you can't define it since it's another package could you make your own type that is a bgp.TimeEntrySlice and offers that?
struct embedding ;)

**Review by ramrunner — CHANGES_REQUESTED** [review]
add a usage() function along with comment explaining what the prog does.
will you keep the default printout? tell me when you are ready and squash the history to one single commit. then i will merge ;)

**Comment by WillYingling** [comment]
I'm sorry, what do you mean by keep the default printout?

**Comment by ramrunner** [comment]
i mean that the way ArchEntryFiles are able to be nicely printed as strings right now is 
because i have implemented a String() function therefore they satisfy the Stringer interface.
if you wanted to change that you should embed the type and provide your own.
i'm fine having the default one. btw the default one is in bgparchive.go and it's
func (a *ArchEntryFile) String() string {
    return fmt.Sprintf("[path:%s date:%v size:%v]", a.Path, a.Sdate, a.Sz)
}

anyway. i like the pull request. thanks for squashing.
merging.

**Review by ramrunner — APPROVED** [review]

**Pull request merged**
